Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -86,7 +86,13 @@ jobs:
         run: sleep 5
 
       - name: Ping
-        run: curl -f http://localhost:80
+        run: |
+          if curl -f http://localhost:80 | grep -q "<title>PC Switch</title>"; then
+              echo "Title found!"
+          else
+              echo "Error: '<title>PC Switch</title>' not found." >&2
+              exit 1
+          fi
 
       - name: Stop container
         run: docker stop remote-switch
